var aliasConfig = {
    appName: ["", "", ""],
    totalPageCount: [],
    largePageWidth: [],
    largePageHeight: [],
    normalPath: [],
    largePath: [],
    thumbPath: [],

    ToolBarsSettings: [],
    TitleBar: [],
    appLogoIcon: ["appLogoIcon"],
    appLogoLinkURL: ["appLogoLinkURL"],
    bookTitle: [],
    bookDescription: [],
    ButtonsBar: [],
    ShareButton: [],
    ShareButtonVisible: ["socialShareButtonVisible"],
    ThumbnailsButton: [],
    ThumbnailsButtonVisible: ["enableThumbnail"],
    ZoomButton: [],
    ZoomButtonVisible: ["enableZoomIn"],
    FlashDisplaySettings: [],
    MainBgConfig: [],
    bgBeginColor: ["bgBeginColor"],
    bgEndColor: ["bgEndColor"],
    bgMRotation: ["bgMRotation"],
    backGroundImgURL: ["mainbgImgUrl", "innerMainbgImgUrl"],
    pageBackgroundColor: ["pageBackgroundColor"],
    flipshortcutbutton: [],
    BookMargins: [],
    topMargin: [],
    bottomMargin: [],
    leftMargin: [],
    rightMargin: [],
    HTMLControlSettings: [],
    linkconfig: [],
    LinkDownColor: ["linkOverColor"],
    LinkAlpha: ["linkOverColorAlpha"],
    OpenWindow: ["linkOpenedWindow"],
    searchColor: [],
    searchAlpha: [],
    SearchButtonVisible: ["searchButtonVisible"],

    productName: [],
    homePage: [],
    enableAutoPlay: ["autoPlayAutoStart"],
    autoPlayDuration: ["autoPlayDuration"],
    autoPlayLoopCount: ["autoPlayLoopCount"],
    BookMarkButtonVisible: [],
    googleAnalyticsID: ["googleAnalyticsID"],
    OriginPageIndex: [],
    HardPageEnable: ["isHardCover"],
    UIBaseURL: [],
    RightToLeft: ["isRightToLeft"],

    LeftShadowWidth: ["leftPageShadowWidth"],
    LeftShadowAlpha: ["pageShadowAlpha"],
    RightShadowWidth: ["rightPageShadowWidth"],
    RightShadowAlpha: ["pageShadowAlpha"],
    ShortcutButtonHeight: [],
    ShortcutButtonWidth: [],
    AutoPlayButtonVisible: ["enableAutoPlay"],
    DownloadButtonVisible: ["enableDownload"],
    DownloadURL: ["downloadURL"],
    HomeButtonVisible: ["homeButtonVisible"],
    HomeURL: ['btnHomeURL'],
    BackgroundSoundURL: ['bacgroundSoundURL'],
    //TableOfContentButtonVisible:["BookMarkButtonVisible"],
    PrintButtonVisible: ["enablePrint"],
    toolbarColor: ["mainColor", "barColor"],
    loadingBackground: ["mainColor", "barColor"],
    BackgroundSoundButtonVisible: ["enableFlipSound"],
    FlipSound: ["enableFlipSound"],
    MiniStyle: ["userSmallMode"],
    retainBookCenter: ["moveFlipBookToCenter"],
    totalPagesCaption: ["totalPageNumberCaptionStr"],
    pageNumberCaption: ["pageIndexCaptionStrs"]
};
var aliasLanguage = {
    frmPrintbtn: ["frmPrintCaption"],
    frmPrintall: ["frmPrintPrintAll"],
    frmPrintcurrent: ["frmPrintPrintCurrentPage"],
    frmPrintRange: ["frmPrintPrintRange"],
    frmPrintexample: ["frmPrintExampleCaption"],
    btnLanguage: ["btnSwicthLanguage"],
    btnTableOfContent: ["btnBookMark"]
}
    ;
var bookConfig = {
    appName: 'flippdf',
    totalPageCount: 0,
    largePageWidth: 1080,
    largePageHeight: 1440,
    normalPath: "files/page/",
    largePath: "files/large/",
    thumbPath: "files/thumb/",

    ToolBarsSettings: "",
    TitleBar: "",
    appLogoLinkURL: "",
    bookTitle: "FLIPBUILDER",
    bookDescription: "",
    ButtonsBar: "",
    ShareButton: "",

    ThumbnailsButton: "",
    ThumbnailsButtonVisible: "Show",
    ZoomButton: "",
    ZoomButtonVisible: "Yes",
    FlashDisplaySettings: "",
    MainBgConfig: "",
    bgBeginColor: "#cccccc",
    bgEndColor: "#eeeeee",
    bgMRotation: 45,
    pageBackgroundColor: "#FFFFFF",
    flipshortcutbutton: "Show",
    BookMargins: "",
    topMargin: 10,
    bottomMargin: 10,
    leftMargin: 10,
    rightMargin: 10,
    HTMLControlSettings: "",
    linkconfig: "",
    LinkDownColor: "#808080",
    LinkAlpha: 0.5,
    OpenWindow: "_Blank",

    BookMarkButtonVisible: 'true',
    productName: 'Demo created by Flip PDF',
    homePage: 'http://www.flipbuilder.com/',
    isFlipPdf: "true",
    TableOfContentButtonVisible: "true",
    searchTextJS: 'javascript/search_config.js',
    searchPositionJS: undefined
};


;
bookConfig.loadingCaption = "Loading";
bookConfig.loadingCaptionColor = "#DDDDDD";
bookConfig.loadingBackground = "#021A25";
// bookConfig.appLogoIcon = "files/mobile-ext/appLogoIcon.png";
bookConfig.appLogoIcon = "";
bookConfig.logoHeight = "40";
bookConfig.logoPadding = "0";
bookConfig.logoTop = "0";
bookConfig.HomeURL = "%first page%";
bookConfig.appLogoOpenWindow = "Blank";
bookConfig.toolbarColor = "#021A25";
bookConfig.iconColor = "#ffffff";
bookConfig.pageNumColor = "#333333";
bookConfig.iconFontColor = "#FFFFFF";
bookConfig.FlipSound = "Enable";
bookConfig.QRCode = "Hide";
bookConfig.HomeButtonVisible = "Hide";
bookConfig.ShareButtonVisible = "Show";
bookConfig.ThumbnailsButtonVisible = "Enable";
bookConfig.thumbnailColor = "#333333";
bookConfig.thumbnailAlpha = "70";
bookConfig.ZoomButtonVisible = "Yes";
bookConfig.BookMarkButtonVisible = "Hide";
bookConfig.TableOfContentButtonVisible = "Show";
bookConfig.bookmarkBackground = "#000000";
bookConfig.bookmarkFontColor = "#cccccc";
bookConfig.SearchButtonVisible = "Hide";
bookConfig.leastSearchChar = "3";
bookConfig.searchFontColor = "#FFFFFF";
bookConfig.PrintButtonVisible = "No";
bookConfig.BackgroundSoundButtonVisible = "Enable";
bookConfig.BackgroundSoundLoop = "-1";
bookConfig.AutoPlayButtonVisible = "Yes";
bookConfig.autoPlayAutoStart = "No";
bookConfig.autoPlayDuration = "9";
bookConfig.autoPlayLoopCount = "1";
bookConfig.minZoomWidth = "700";
bookConfig.minZoomHeight = "518";
bookConfig.mouseWheelFlip = "yes";
bookConfig.DownloadButtonVisible = "Hide";
bookConfig.bgBeginColor = "#008CCE";
bookConfig.bgEndColor = "#9AFFFF";
bookConfig.bgMRotation = "90";
bookConfig.backGroundImgURL = "files/mobile-ext/backGroundImgURL.jpg";
bookConfig.LeftShadowWidth = "90";
bookConfig.LeftShadowAlpha = "0.6";
bookConfig.RightShadowWidth = "55";
bookConfig.RightShadowAlpha = "0.6";
bookConfig.HardPageEnable = "No";
bookConfig.hardCoverBorderWidth = "8";
bookConfig.borderColor = "#572F0D";
bookConfig.outerCoverBorder = "Yes";
bookConfig.cornerRound = "8";
bookConfig.pageBackgroundColor = "#FFFFFF";
bookConfig.flipshortcutbutton = "Show";
bookConfig.BindingType = "side";
bookConfig.RightToLeft = "No";
bookConfig.flippingTime = "0.6";
bookConfig.retainBookCenter = "Yes";
bookConfig.FlipStyle = "Flip";
bookConfig.showDoublePage = "Yes";
bookConfig.topMargin = "10";
bookConfig.bottomMargin = "10";
bookConfig.leftMargin = "10";
bookConfig.rightMargin = "10";
bookConfig.leftMarginOnMobile = "0";
bookConfig.topMarginOnMobile = "0";
bookConfig.rightMarginOnMobile = "0";
bookConfig.bottomMarginOnMobile = "0";
bookConfig.maxWidthToSmallMode = "400";
bookConfig.maxHeightToSmallMode = "300";
bookConfig.LinkDownColor = "#800080";
bookConfig.LinkAlpha = "0.2";
bookConfig.OpenWindow = "Blank";
bookConfig.showLinkHint = "No";
bookConfig.searchFontColor = "#FFFDDD";
bookConfig.totalPageCount = 82; //總頁數
bookConfig.largePageWidth = 1800;
bookConfig.largePageHeight = 2546;;
bookConfig.securityType = "1";
// bookConfig.bookTitle = "30�𪂹撟渡�敹萄����";
bookConfig.productName = "Flip PDF Professional";
bookConfig.homePage = "http://www.flipbuilder.com";
bookConfig.searchPositionJS = "mobile/javascript/search_config.js";
bookConfig.searchTextJS = "mobile/javascript/search_config.js";
bookConfig.normalPath = "files/mobile/";
bookConfig.largePath = "files/mobile/";
bookConfig.thumbPath = "files/thumb/";
bookConfig.userListPath = "files/extfiles/users.js";
bookConfig.UIBaseURL = 'mobile/';
var language = [{
    language: "Chinese(Tranditional)",
    // btnFirstPage: "蝚砌���",
    // btnNextPage: "銝衤���",
    // btnLastPage: "����𦒘���",
    // btnPrePage: "��滢���",
    // btnDownload: "銝贝��",
    // btnPrint: "��枏㫲",
    // btnSearch: "��𦦵揣",
    // btnClearSearch: "皜��膄",
    // frmSearchPrompt: "Clear",
    // btnBookMark: "�𤌍��",
    // btnHelp: "撟怠𨭌",
    // btnHome: "Home",
    // btnFullScreen: "�典��",
    // btnDisableFullScreen: "�芦撅�",
    // btnSoundOn: "��㯄�贝�脤𨺗",
    // btnSoundOff: "��𣈯�㕑�脤𨺗",
    // btnShareEmail: "��鈭�",
    // btnSocialShare: "��见�见�鈭�",
    // btnZoomIn: "�𦆮憭�",
    // btnZoomOut: "蝮桀��",
    // btnDragToMove: "��硋��/蝘餃��",
    // btnAutoFlip: "�䌊��閧蕃��",
    // btnStopAutoFlip: "�𨀣迫蝧駁�",
    // btnGoToHome: "餈𥪜�硺蜓��",
    // frmHelpCaption: "撟怠𨭌",
    // frmHelpTip1: "�虾隞仿�蹱�𢠃�脰�峕𦆮憭扳�𣇉葬撠�",
    // frmHelpTip2: "��硋�閖��𢒰���贝�鍦虾隞仿�脰�𣬚蕃��",
    // frmPrintCaption: "��枏㫲蝒堒藁",
    // frmPrintBtnCaption: "��枏㫲",
    // frmPrintPrintAll: "��枏㫲����厰��𢒰",
    // frmPrintPrintCurrentPage: "��枏㫲�訜��漤�",
    // frmPrintPrintRange: "��枏㫲����㵪��",
    // frmPrintExampleCaption: "靘见�嚗�2,5,8-26",
    // frmPrintPreparePage: "甇�銁皞硋�䠷�嚗�",
    // frmPrintPrintFailed: "��枏㫲憭望�梹��",
    // pnlSearchInputInvalid: "嚗��撠煾�閬�頛詨��3�见�㛖泵嚗�",
    // loginCaption: "�蒈��",
    // loginInvalidPassword: "雿㰘撓�亦�撖�蝣潔�齿迤蝣綽�",
    // loginPasswordLabel: "撖�蝣潘��",
    // loginBtnLogin: "�蒈��",
    // loginBtnCancel: "��𡝗��",
    // btnThumb: "縮略圖",
    // lblPages: "���彍嚗�",
    // lblPagesFound: "�𪄳�����彍嚗�",
    // lblPageIndex: "��",
    // btnAbout: "��靝��",
    // frnAboutCaption: "��靝�擧�穃��",
    // btnSinglePage: "�鱓��",
    // btnDoublePage: "��䠷�",
    // btnSwicthLanguage: "����𥡝�噼�",
    // tipChangeLanguage: "隢见銁銝钅𢒰�豢���蝔株�噼�",
    // btnMoreOptionsLeft: "�凒憭𡁻�豢��",
    // btnMoreOptionsRight: "�凒憭𡁻�豢��",
    // btnFit: "�䌊��閖�拇��",
    // smallModeCaption: "暺墧�𠰴�典��",
    // btnAddAnnotation: "��䭾釣���",
    // btnAnnotation: "瘜券�见�𡑒”",
    // FlipPageEditor_SaveAndExit: "靽嘥�睃僎���枂",
    // FlipPageEditor_Exit: "���枂",
    // DrawToolWindow_Redo: "��滚��",
    // DrawToolWindow_Undo: "�伃�啹",
    // DrawToolWindow_Clear: "皜��膄",
    // DrawToolWindow_Brush: "蝑���",
    // DrawToolWindow_Width: "蝑���撖砍漲",
    // DrawToolWindow_Alpha: "蝑����𤩺�𤾸漲",
    // DrawToolWindow_Color: "蝑���憿磰𠧧",
    // DrawToolWindow_Eraser: "�𣑐�膄",
    // DrawToolWindow_Rectangular: "�畆敶�",
    // DrawToolWindow_Ellipse: "璈Ｗ��",
    // TStuff_BorderWidth: "�𦠜�撖砍葆",
    // TStuff_BorderAlph: "�𦠜��𤩺�𤾸漲",
    // TStuff_BorderColor: "摮烾�娪�磰𠧧",
    // DrawToolWindow_TextNote: "���𧋦��瘜�",
    // AnnotMark: "�㮾蝪�",
    // lastpagebtnHelp: "����𦒘���",
    // firstpagebtnHelp: "蝚砌���",
    // homebtnHelp: "餈𥪜�鮋�㚚�",
    // aboubtnHelp: "��靝��",
    // screenbtnHelp: "�銁銝��见�峕㟲��蝒堒藁銝剜�㯄�贝府��厩鍂蝔见��",
    // helpbtnHelp: "��㯄�见鼠�𨭌蝒堒藁",
    // searchbtnHelp: "敺墧㮾��銝剜�𦦵揣",
    // pagesbtnHelp: "��鞱汗撠誩�𠰴�鞟�蝮桃裦���",
    // bookmarkbtnHelp: "��㯄�讠𤌍��",
    // AnnotmarkbtnHelp: "��㯄�𧢲㮾蝪�",
    // printbtnHelp: "��枏㫲撠誩�𠰴��",
    // soundbtnHelp: "��见���㚚�𣈯�厩��脤𨺗",
    // sharebtnHelp: "�䔄��瘨���",
    // socialSharebtnHelp: "�䔄��瘨���",
    // zoominbtnHelp: "�𦆮憭�",
    // downloadbtnHelp: "銝贝�匧恐�喳��",
    // pagemodlebtnHelp: "�鱓����屸�䠷�",
    // languagebtnHelp: "����𥡝�噼�",
    // annotationbtnHelp: "瘛餃�䭾鸌瘜�",
    // addbookmarkbtnHelp: "�䌊摰𡁶儔�㮾蝪�",
    // removebookmarkbtnHelp: "蝘駁膄�㮾蝪�",
    // updatebookmarkbtnHelp: "�凒�鰵�㮾蝪�",
    // btnShoppingCart: "鞈潛�頠𦠜�厰��",
    // Help_ShoppingCartbtn: "鞈潛�頠�",
    // Help_btnNextPage: "銝钅�",
    // Help_btnPrePage: "銝𢠃�",
    // Help_btnAutoFlip: "�䌊��閧蕃��",
    // Help_StopAutoFlip: "�𨀣迫�䌊��閧蕃��",
    // btnaddbookmark: "瘛餃��",
    // btndeletebookmark: "�⏛�膄",
    // btnupdatebookmark: "�凒�鰵",
    // frmyourbookmarks: "雿删��㮾蝪�",
    // frmitems: "���𤌍",
    // DownloadFullPublication: "�㟲隞賢枂����",
    // DownloadCurrentPage: "�訜��漤�",
    // DownloadAttachedFiles: "��隞�",
    // lblLink: "��鈭恍��𦻖",
    // btnCopy: "敺拙���厰��",
    // infCopyToClipboard: "Your browser does not support clipboard. ",
    // restorePage: "�糓�炏敺硺�𦠜活��雿滨蔭��见��",
    // tmpl_Backgoundsoundon: "�峕艶�𨺗璅����",
    // tmpl_Backgoundsoundoff: "�峕艶�𨺗璅����",
    // tmpl_Flipsoundon: "蝧駁��脤��",
    // tmpl_Flipsoundoff: "蝧駁��脤��",
    // Help_PageIndex: "�訜��漤�蝣�",
    // tmpl_PrintPageRanges: "�������",
    // tmpl_PrintPreview: "��鞱汗",
    // btnSelection: "�豢������",
    // loginNameLabel: "�函���滚��:",
    // btnGotoPage: "頝唾秐",
    // btnSettings: "閮剔蔭",
    // soundSettingTitle: "�脤𨺗�賊�",
    // closeFlipSound: "蝧駁��脤�钅��",
    // closeBackgroundSound: "�峕艶�脤�钅��",
    // frmShareCaption: "��鈭�",
    // frmShareLinkLabel: "���𦻖:",
    // frmShareBtnCopy: "敺拙�",
    // frmShareItemsGroupCaption: "��见�见�鈭�",
    // TAnnoActionPropertyStuff_GotoPage: "頧匧���",
    // btnPageBack: "��𡡞��",
    // btnPageForward: "��漤��",
    // SelectTextCopy: "���𧋦敺拙�",
    // selectCopyButton: "敺拙�",
    // TStuffCart_TypeCart: "鞈潛�頠�",
    // TStuffCart_DetailedQuantity: "�彍���",
    // TStuffCart_DetailedPrice: "�寞聢",
    // ShappingCart_Close: "��𣈯��",
    // ShappingCart_CheckOut: "隞䀹狡",
    // ShappingCart_Item: "���𤌍",
    // ShappingCart_Total: "蝮質��",
    // ShappingCart_AddCart: "瘛餃�惩�鞈潛�頠�",
    // ShappingCart_InStock: "��㕑疏",
    // TStuffCart_DetailedCost: "�贝祥",
    // TStuffCart_DetailedTime: "鈭方疏�����",
    // TStuffCart_DetailedDay: "憭拇彍(s)",
    // ShappingCart_NotStock: "�∟疏",
    // btnCrop: "�⏛���",
    // btnDragButton: "��硋��",
    // btnFlipBook: "蝧駁��㮾",
    // btnSlideMode: "瘞游像皛穃�閧蕃��",
    // btnSinglePageMode: "�鱓��璅∪��",
    // btnVertical: "銝𠹺�讠蕃���讛汗",
    // btnHotizontal: "撌血𢰧蝧駁��讛汗",
    // btnClose: "��𣈯��",
    // btnDoublePage: "��䠷�",
    // btnBookStatus: "閬硋��",
    // checkBoxInsert: "��惩�亦訜��滨雯��",
    // lblLast: "�蹱糓��敺䔶�����",
    // lblFirst: "�蹱糓蝚砌�����",
    // lblFullscreen: "暺墧�𦠜䰻��见�典��",
    // lblName: "��滨迂",
    // lblPassword: "撖�蝣�",
    // lblLogin: "�蒈��",
    // lblCancel: "��𡝗��",
    // lblNoName: "�鍂����滨迂銝滩�賜�箇征��",
    // lblNoPassword: "撖�蝣潔�滩�賜�箇征��",
    // lblNoCorrectLogin: "隢贝撓�交迤蝣箇��鍂����滚���蝣潦��",
    // btnVideo: "閬㚚朌�𧞄撱�",
    // btnSlideShow: "撟餌����𦆮���",
    // pnlSearchInputInvalid: "嚗��撠煾�閬�頛詨��3�见�㛖泵嚗�",
    // btnDragToMove: "��硋��/蝘餃��",
    // btnPositionToMove: "皛煾�删宏���",
    // lblHelp1: "��硋�閖��𢒰閫埝䰻���",
    // lblHelp2: "��匧�拐�𧢲𦆮憭改�𣬚葬撠�",
    // lblCopy: "銴�ˊ",
    // lblAddToPage: "瘛餃�惩����𢒰",
    // lblPage: "��",
    // lblTitle: "璅䠷��",
    // lblEdit: "蝺刻摩",
    // lblDelete: "��𣳇膄",
    // lblRemoveAll: "��𣳇膄�����",
    // tltCursor: "�㗇��",
    // tltAddHighlight: "瘛餃�𣳇�䀝漁",
    // tltAddTexts: "瘛餃�䭾����",
    // tltAddShapes: "瘛餃�惩耦��",
    // tltAddNotes: "瘛餃�䭾釣���",
    // tltAddImageFile: "瘛餃�惩蔣�𤩺�娍��",
    // tltAddSignature: "瘛餃�删偷���",
    // tltAddLine: "瘛餃�删凒蝺�",
    // tltAddArrow: "瘛餃�删悌��",
    // tltAddRect: "瘛餃�删畆敶�",
    // tltAddEllipse: "瘛餃�䭾岷���",
    // lblDoubleClickToZoomIn: "��蹱�𢠃�脰�峕𦆮憭扼��",
    // frmShareCaption: "��鈭�",
    // frmShareLabel: "��鈭�",
    // frmShareInfo: "�典虾隞亥�閖��𧑐��鈭急𧋦�枂����銝剖�滨冗鈭斤雯蝯～���蘨��暺墧�𠹺�钅𢒰���㮾��㗇�厰�𨰻��",
    // frminsertLabel: "��鍦�亙�蝬脩��",
    // frminsertInfo: "雿輻鍂銝钅𢒰��隞�Ⅳ�𧋦�枂����銝剖���亙�雿删�蝬脩�踺��",
    btnQRCode: "Click to scan QR code",
    btnRotateLeft: "Rotate Left",
    lblSelectMode: "Select view mode please."
}, {
    language: "English",
    btnFirstPage: "First",
    btnNextPage: "Next Page",
    btnLastPage: "Last",
    btnPrePage: "Previous Page",
    btnDownload: "Download",
    btnPrint: "Print",
    btnSearch: "Search",
    btnClearSearch: "Clear",
    frmSearchPrompt: "Clear",
    btnBookMark: "Table of content",
    btnHelp: "Help",
    btnHome: "Home",
    btnFullScreen: "Enable FullScreen",
    btnDisableFullScreen: "Disable FullScreen",
    btnSoundOn: "Sound On",
    btnSoundOff: "Sound Off",
    btnShareEmail: "Share",
    btnSocialShare: "Social Share",
    btnZoomIn: "Zoom In",
    btnZoomOut: "Zoom Out",
    btnDragToMove: "Move by mouse drag",
    btnAutoFlip: "Auto Flip",
    btnStopAutoFlip: "Stop Auto Flip",
    btnGoToHome: "Return Home",
    frmHelpCaption: "Help",
    frmHelpTip1: "Double click to zoom in or out",
    frmHelpTip2: "Drag the page corner to view",
    frmPrintCaption: "Print",
    frmPrintBtnCaption: "Print",
    frmPrintPrintAll: "Print All Pages",
    frmPrintPrintCurrentPage: "Print Current Page",
    frmPrintPrintRange: "Print Range",
    frmPrintExampleCaption: "Example: 2,5,8-26",
    frmPrintPreparePage: "Preparing Page:",
    frmPrintPrintFailed: "Print Failed:",
    pnlSearchInputInvalid: "(Minimal request length is 3 symbols)",
    loginCaption: "Login",
    loginInvalidPassword: "Not a valid password!",
    loginPasswordLabel: "Password:",
    loginBtnLogin: "Login",
    loginBtnCancel: "Cancel",
    btnThumb: "Thumbnails",
    lblPages: "Pages:",
    lblPagesFound: "Pages:",
    lblPageIndex: "Page",
    btnAbout: "About",
    frnAboutCaption: "About & Contact",
    btnSinglePage: "Single Page",
    btnDoublePage: "Double Page",
    btnSwicthLanguage: "Switch Language",
    tipChangeLanguage: "Please select a language below...",
    btnMoreOptionsLeft: "More Options",
    btnMoreOptionsRight: "More Options",
    btnFit: "Fit Window",
    smallModeCaption: "Click to view in fullscreen",
    btnAddAnnotation: "Add Annotations",
    btnAnnotation: "Annotations",
    FlipPageEditor_SaveAndExit: "Save and Exit",
    FlipPageEditor_Exit: "Exit",
    DrawToolWindow_Redo: "Redo",
    DrawToolWindow_Undo: "Undo",
    DrawToolWindow_Clear: "Clear",
    DrawToolWindow_Brush: "Brush",
    DrawToolWindow_Width: "Width",
    DrawToolWindow_Alpha: "Alpha",
    DrawToolWindow_Color: "Color",
    DrawToolWindow_Eraser: "Eraser",
    DrawToolWindow_Rectangular: "Rectangular",
    DrawToolWindow_Ellipse: "Ellipse",
    TStuff_BorderWidth: "Border Width",
    TStuff_BorderAlph: "Border Alpha",
    TStuff_BorderColor: "Border Color",
    DrawToolWindow_TextNote: "Text Note",
    AnnotMark: "Book Mark",
    lastpagebtnHelp: "Last page",
    firstpagebtnHelp: "First page",
    homebtnHelp: "Return to home page",
    aboubtnHelp: "About",
    screenbtnHelp: "Open this application in full-screen mode",
    helpbtnHelp: "Show help",
    searchbtnHelp: "Search from pages",
    pagesbtnHelp: "Take a look at the thumbnail of this brochure",
    bookmarkbtnHelp: "Open Bookmark",
    AnnotmarkbtnHelp: "Open Table of content",
    printbtnHelp: "Print the brochure",
    soundbtnHelp: "Turn on or off the sound",
    sharebtnHelp: "Send Email to",
    socialSharebtnHelp: "Social Share",
    zoominbtnHelp: "Zoom in",
    downloadbtnHelp: "Downdlaod this brochure",
    pagemodlebtnHelp: "Switch Single and double page mode",
    languagebtnHelp: "Switch Lauguage",
    annotationbtnHelp: "Add Annotation",
    addbookmarkbtnHelp: "Add Bookmark",
    removebookmarkbtnHelp: "Remove BookMark",
    updatebookmarkbtnHelp: "Update Bookmark",
    btnShoppingCart: "Shopping Cart",
    Help_ShoppingCartbtn: "Shopping Cart",
    Help_btnNextPage: "Next page",
    Help_btnPrePage: "Previous page",
    Help_btnAutoFlip: "Auto filp",
    Help_StopAutoFlip: "Stop atuo filp",
    btnaddbookmark: "Add",
    btndeletebookmark: "Delete",
    btnupdatebookmark: "Update",
    frmyourbookmarks: "Your bookmarks",
    frmitems: "items",
    DownloadFullPublication: "Full Publication",
    DownloadCurrentPage: "Current Page",
    DownloadAttachedFiles: "Attached Files",
    lblLink: "Link",
    btnCopy: "Copy Button",
    infCopyToClipboard: "Your browser does not support clipboard. ",
    restorePage: "Would you like to restore previous session",
    tmpl_Backgoundsoundon: "Background Sound On",
    tmpl_Backgoundsoundoff: "Background Sound Off",
    tmpl_Flipsoundon: "Flip Sound On",
    tmpl_Flipsoundoff: "Flip Sound Off",
    Help_PageIndex: "The current page number",
    tmpl_PrintPageRanges: "PAGE RANGES",
    tmpl_PrintPreview: "PREVIEW",
    btnSelection: "Select Text",
    loginNameLabel: "Name:",
    btnGotoPage: "Go",
    btnSettings: "Setting",
    soundSettingTitle: "Sound Setting",
    closeFlipSound: "Close Flip Sound",
    closeBackgroundSound: "Close Backgorund Sound",
    frmShareCaption: "Share",
    frmShareLinkLabel: "Link:",
    frmShareBtnCopy: "Copy",
    frmShareItemsGroupCaption: "Social Share",
    TAnnoActionPropertyStuff_GotoPage: "Go to page",
    btnPageBack: "Backward",
    btnPageForward: "Forward",
    SelectTextCopy: "Copy Selected Text",
    selectCopyButton: "Copy",
    TStuffCart_TypeCart: "Shopping Cart",
    TStuffCart_DetailedQuantity: "Quantity",
    TStuffCart_DetailedPrice: "Price",
    ShappingCart_Close: "Close",
    ShappingCart_CheckOut: "Checkout",
    ShappingCart_Item: "Item",
    ShappingCart_Total: "Total",
    ShappingCart_AddCart: "Add to cart",
    ShappingCart_InStock: "In Stock",
    TStuffCart_DetailedCost: "Shipping cost",
    TStuffCart_DetailedTime: "Delivery time",
    TStuffCart_DetailedDay: "day(s)",
    ShappingCart_NotStock: "Not enough in stock",
    btnCrop: "Crop",
    btnDragButton: "Drag",
    btnFlipBook: "Flip Book",
    btnSlideMode: "Slide Mode",
    btnSinglePageMode: "Single Page Mode",
    btnVertical: "Vertical Mode",
    btnHotizontal: "Horizontal Mode",
    btnClose: "Close",
    btnDoublePage: "Double Page",
    btnBookStatus: "Book View",
    checkBoxInsert: "Insert Current Page",
    lblLast: "This is the last page.",
    lblFirst: "This is the first page.",
    lblFullscreen: "Click to view in fullscreen",
    lblName: "Name",
    lblPassword: "Password",
    lblLogin: "Login",
    lblCancel: "Cancel",
    lblNoName: "User name can not be empty.",
    lblNoPassword: "Password can not be empty.",
    lblNoCorrectLogin: "Please enter the correct user name and password.",
    btnVideo: "Video Gallery",
    btnSlideShow: "Slide Show",
    pnlSearchInputInvalid: "(Minimal request length is 3 symbols)",
    btnDragToMove: "Move by mouse drag",
    btnPositionToMove: "Move by mouse position",
    lblHelp1: "Drag the page corner to view",
    lblHelp2: "Double click to zoom in, out",
    lblCopy: "Copy",
    lblAddToPage: "add to page",
    lblPage: "Page",
    lblTitle: "Title",
    lblEdit: "Edit",
    lblDelete: "Delete",
    lblRemoveAll: "Remove All",
    tltCursor: "cursor",
    tltAddHighlight: "add highlight",
    tltAddTexts: "add texts",
    tltAddShapes: "add shapes",
    tltAddNotes: "add notes",
    tltAddImageFile: "add image file",
    tltAddSignature: "add signature",
    tltAddLine: "add line",
    tltAddArrow: "add arrow",
    tltAddRect: "add rect",
    tltAddEllipse: "add ellipse",
    lblDoubleClickToZoomIn: "Double click to zoom in.",
    frmShareCaption: "Share",
    frmShareLabel: "Share",
    frmShareInfo: "You can easily share this publication to social networks.Just cilck the appropriate button below.",
    frminsertLabel: "Insert to Site",
    frminsertInfo: "Use the code below to embed this publication to your website.",
    btnQRCode: "Click to scan QR code",
    btnRotateLeft: "Rotate Left",
    lblSelectMode: "Select view mode please."
}];;

function orgt(s) {
    return binl2hex(core_hx(str2binl(s), s.length * chrsz));
};;
var pageEditor = {
    "setting": {
        "annoPlaying": "true",
        "shoppingCartHTML": "false",
        "shoppingCartOptinon": {
            "type": "PayPal",
            "paypal": "",
            "method": "POST",
            "sandbox": "false",
            "address": "",
            "theme": "",
            "body": "Hi xxx<br/>   I\'m going to buy below product(s):<br/>    ${shopping}<br/>Full Name",
            "showPrice": "true",
            "showTime": "true"
        }
    },
    "pageAnnos": [
        [],
        [],
        [{
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "201912132320675",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link2",
                "x": "0.07895444160731085",
                "y": "0.10452671964270868",
                "width": "0.1679881736325763",
                "height": "0.04038532349831926",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792"
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323209044",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link3",
                "x": "0.08399408681628814",
                "y": "0.10452671964270868",
                "width": "0.16462841015992474",
                "height": "0.03800971623371224",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "5"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323205914",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link1",
                "x": "0.08231420507996237",
                "y": "0.2636924063713787",
                "width": "0.30573847601128884",
                "height": "0.03919751986601575",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "17"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "201912132320618",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link2",
                "x": "0.0856739685526139",
                "y": "0.3777215550725154",
                "width": "0.3107781212202661",
                "height": "0.03800971623371224",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "27"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323202170",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link12",
                "x": "0.08735385028893966",
                "y": "0.41454346767392414",
                "width": "0.07391479639833357",
                "height": "0.01900485811685612",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "28"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323204538",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link13",
                "x": "0.0856739685526139",
                "y": "0.6841748922068204",
                "width": "0.08063432334363661",
                "height": "0.01900485811685612",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "38"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323203772",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link14",
                "x": "0.0856739685526139",
                "y": "0.8160210953925098",
                "width": "0.07895444160731085",
                "height": "0.01900485811685612",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "46"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323204284",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link15",
                "x": "0.08903373202526542",
                "y": "0.8872893133307201",
                "width": "0.07559467813465932",
                "height": "0.01900485811685612",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "49"
            }
        }],
        [{
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323208433",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link3",
                "x": "0.08063432334363661",
                "y": "0.04988775255674732",
                "width": "0.30741835774761456",
                "height": "0.036821912601408734",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "53"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323205864",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link4",
                "x": "0.08231420507996237",
                "y": "0.6996163394267659",
                "width": "0.30573847601128884",
                "height": "0.03563410896910523",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "113"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323208678",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link5",
                "x": "0.08231420507996237",
                "y": "0.9134209932413974",
                "width": "0.19990592662276577",
                "height": "0.03325850170449821",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "132"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323202246",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link6",
                "x": "0.0856739685526139",
                "y": "0.08789746879045957",
                "width": "0.17302781884155355",
                "height": "0.02019266174915963",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "54"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323205920",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link7",
                "x": "0.0856739685526139",
                "y": "0.15916568672867001",
                "width": "0.17302781884155355",
                "height": "0.01900485811685612",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "62"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323209660",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link8",
                "x": "0.08399408681628814",
                "y": "0.24706315551912958",
                "width": "0.1763875823142051",
                "height": "0.01900485811685612",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "67"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323202077",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link9",
                "x": "0.08735385028893966",
                "y": "0.4181068785708347",
                "width": "0.1713479371052278",
                "height": "0.017817054484552616",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "83"
            }
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323209466",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link10",
                "x": "0.08063432334363661",
                "y": "0.5891506016225397",
                "width": "0.1310307754334095",
                "height": "0.11878036323035077",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792"
        }, {
            "annotype": "com.mobiano.flipbook.pageeditor.TAnnoLink",
            "annoId": "2019121323207608",
            "alpha": "1",
            "overColor": "16777215",
            "downColor": "16777215",
            "outColor": "11184810",
            "overAlpha": "0.2",
            "downAlpha": "0.2",
            "outAlpha": "0",
            "pageViewedBool": "true",
            "ellipseH": "0",
            "ellipseW": "0",
            "location": {
                "tannoName": "link11",
                "x": "0.08063432334363661",
                "y": "0.5903384052548433",
                "width": "0.18445101464856875",
                "height": "0.02084595374692656",
                "rotation": "0",
                "reflection": "false",
                "reflectionType": "0",
                "reflectionAlpha": "0",
                "pageWidth": "595.28",
                "pageHeight": "841.89"
            },
            "hint": {
                "hintShapeColor": "0",
                "hintShapeColor2": "8388736",
                "hintShapeAlpha": "1",
                "hintW": "0",
                "hintH": "0",
                "hintAuto": "true",
                "hintShapeType": "2",
                "text": ""
            },
            "shadow": {
                "hasDropShadow": "false",
                "shadowDistance": "4",
                "shadowAngle": "270",
                "shadowColor": "0",
                "shadowAlpha": "0.6",
                "shadowBlurX": "4",
                "shadowBlurY": "4"
            },
            "highlightsBool": "false",
            "linkStatus": "1",
            "mouseOver": "false",
            "borderColor": "16737792",
            "action": {
                "triggerEventType": "mouseUp",
                "actionType": "com.mobiano.flipbook.pageeditor.TAnnoActionGotoPage",
                "pageIndex": "100"
            }
        }],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
    ]
};
bookConfig.isFlipPdf = false;

bookConfig.hideMiniFullscreen = true;
if (language && language.length > 0 && language[0] && language[0].language) {
    bookConfig.language = language[0].language;
}

try {
    for (var i = 0; pageEditor != undefined && i < pageEditor.length; i++) {
        if (pageEditor[i].length == 0) {
            continue;
        }
        for (var j = 0; j < pageEditor[i].length; j++) {
            var anno = pageEditor[i][j];
            if (anno == undefined) continue;
            if (anno.overAlpha == undefined) {
                anno.overAlpha = bookConfig.LinkAlpha;
            }
            if (anno.outAlpha == undefined) {
                anno.outAlpha = 0;
            }
            if (anno.downAlpha == undefined) {
                anno.downAlpha = bookConfig.LinkAlpha;
            }
            if (anno.overColor == undefined) {
                anno.overColor = bookConfig.LinkDownColor;
            }
            if (anno.downColor == undefined) {
                anno.downColor = bookConfig.LinkDownColor;
            }
            if (anno.outColor == undefined) {
                anno.outColor = bookConfig.LinkDownColor;
            }
            if (anno.annotype == 'com.mobiano.flipbook.pageeditor.TAnnoLink') {
                anno.alpha = bookConfig.LinkAlpha;
            }
        }
    }
} catch (e) {
}
try {
    $.browser.device = 2;
} catch (ee) {
}